apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nuxt-app
  labels:
    app: nuxt-app
spec:
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      containers:
        - name: nuxt
          image: gcr.io/gke-sample-201809/nuxt-rails-gke-sample-nuxt
          env:
            - name: HOST
              value: 0.0.0.0
            - name: API_URL
              value: 35.184.158.167
          ports:
            - containerPort: 3000
          # command: ["sleep", "1000"]
          command: ["yarn", "nuxt", "start", "-p", "3000"]
          # command: ["HOST=0.0.0.0", "API_URL=35.189.134.49", "yarn", "nuxt", "start"]
