apiVersion: v1
kind: Service
metadata:
  name: nuxt
  labels:
    app: nuxt
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: nuxt-app
