default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: myapp_development
  port: <%= ENV['DATABASE_PORT'] %>

test:
  <<: *default
  database: myapp_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: myapp
  port: <%= ENV['DATABASE_PORT'] %>
